server:
  port: 8080

spring:
  application:
    name: ms-intercorp-gw
  cloud:
    gateway:
      routes:
        - id: ms-intercorp-task
          uri: http://localhost:8081
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1